import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { ExampleCreator, ExamplesView } from "../components/example";

const Home: NextPage = () => {
  const { data: examples } = trpc.useQuery(["example.getAll"]);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Create <span>T3</span> App (Monorepo Version)
        </h1>
        <h3>Examples</h3>
        <ExamplesView examples={examples} />
        <ExampleCreator />
      </div>
    </>
  );
};

export default Home;
